#Application Configuration
server:
  port: 8091

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"